[package]
name = "subgraph-wasm-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "4.2.2"
semver = "1.0.20"
anyhow = "1.0.75"
ethabi = "17.2"
web3 = "0.18.0"
num-bigint = { version = "0.2.6", features = [] }
serde_json = { version = "1.0.107", features = [] }