[package]
name = "subgraph-wasm-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bigdecimal = { version = "0.4.2", features = ["serde"] }
env_logger = "0.10.0"
ethabi = "18.0.0"
hex = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.20"
num-bigint = "0.4.4"
num-traits = "0.2.17"
proc-macro2 = "1.0.69"
quote = "1.0.33"
semver = "1.0.20"
serde = "1.0.189"
serde_json = "1.0.107"
syn = "2.0.38"
thiserror = "1.0.49"
wasmer = "4.2.2"
web3 = "0.19.0"
